package com.hidalgocarlos.inventory;

import com.hidalgocarlos.inventory.model.Product;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.math.BigDecimal;

@SpringBootApplication
public class InventorySystemSpringBootAngularJsApplication {

	public static void main(String[] args) {
		SpringApplication.run(InventorySystemSpringBootAngularJsApplication.class, args);

		// Test creation of a Product instance
		Product product = new Product(null, "Sample product", "This is a sample product desciption.",
				new BigDecimal("19.99"), 150);

		// Print the product details to verify creation
		System.out.println("Product created: " + product);
		// Note: The toString method is generated by Lombok, so it will print
		// the product details in a readable format.
		// If you have Lombok configured correctly, it will show the productId as null
		// since it has not been persisted to the database yet.

	}

}
